import { X, Calendar, User, Clock, Download, Printer } from 'lucide-react'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import { useRef } from 'react'

export default function ReportModal({ plan, onClose }) {
  const reportRef = useRef(null)

  if (!plan || !plan.tasks) {
    return null
  }

  const chartData = plan.tasks.map(task => ({
    name: task.name, // Display full name
    fullName: task.name,
    start: task.start_day,
    duration: task.duration,
    end: task.start_day + task.duration
  }))

  const handleDownloadPDF = async () => {
    try {
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      })

      const pageWidth = pdf.internal.pageSize.getWidth()
      const pageHeight = pdf.internal.pageSize.getHeight()
      const margin = 20
      const contentWidth = pageWidth - (margin * 2)
      let yPos = margin

      // Helper function to check if we need a new page
      const checkNewPage = (requiredSpace) => {
        if (yPos + requiredSpace > pageHeight - margin) {
          pdf.addPage()
          yPos = margin
          // Add page number
          pdf.setFontSize(8)
          pdf.setTextColor(150, 150, 150)
          pdf.text(`Page ${pdf.internal.getNumberOfPages()}`, pageWidth / 2, pageHeight - 10, { align: 'center' })
          pdf.setTextColor(0, 0, 0)
          return true
        }
        return false
      }

      // Add watermark to all pages
      const addWatermark = () => {
        pdf.setFontSize(8)
        pdf.setTextColor(200, 200, 200)
        pdf.text('Generated by Incept AI', pageWidth - margin, pageHeight - 10, { align: 'right' })
        pdf.setTextColor(0, 0, 0)
      }

      // ========================================
      // COVER PAGE / HEADER
      // ========================================
      
      // Black header bar
      pdf.setFillColor(0, 0, 0)
      pdf.rect(0, 0, pageWidth, 50, 'F')
      
      // Title
      pdf.setTextColor(255, 255, 255)
      pdf.setFontSize(28)
      pdf.setFont('helvetica', 'bold')
      pdf.text('PROJECT TIMELINE REPORT', margin, 25)
      
      // Subtitle
      pdf.setFontSize(11)
      pdf.setFont('helvetica', 'normal')
      pdf.text('AI-Generated Project Plan', margin, 38)
      
      yPos = 60

      // ========================================
      // 1. PROJECT OVERVIEW
      // ========================================
      
      pdf.setTextColor(0, 0, 0)
      pdf.setFontSize(16)
      pdf.setFont('helvetica', 'bold')
      pdf.text('PROJECT OVERVIEW', margin, yPos)
      yPos += 10

      // Project details box
      pdf.setFillColor(250, 250, 250)
      pdf.roundedRect(margin, yPos, contentWidth, 35, 2, 2, 'F')
      pdf.setDrawColor(220, 220, 220)
      pdf.roundedRect(margin, yPos, contentWidth, 35, 2, 2, 'S')
      
      pdf.setFontSize(11)
      pdf.setFont('helvetica', 'bold')
      pdf.text('Project Name:', margin + 5, yPos + 8)
      pdf.setFont('helvetica', 'normal')
      pdf.text(plan.project_name, margin + 40, yPos + 8)
      
      pdf.setFont('helvetica', 'bold')
      pdf.text('Total Duration:', margin + 5, yPos + 16)
      pdf.setFont('helvetica', 'normal')
      pdf.text(`${plan.total_duration} days`, margin + 40, yPos + 16)
      
      pdf.setFont('helvetica', 'bold')
      pdf.text('Date Generated:', margin + 5, yPos + 24)
      pdf.setFont('helvetica', 'normal')
      const generatedDate = new Date().toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      })
      pdf.text(generatedDate, margin + 40, yPos + 24)
      
      yPos += 45

      // ========================================
      // 2. EXECUTIVE SUMMARY
      // ========================================
      
      checkNewPage(30)
      pdf.setFontSize(16)
      pdf.setFont('helvetica', 'bold')
      pdf.text('EXECUTIVE SUMMARY', margin, yPos)
      yPos += 8

      // Generate executive summary
      const taskTypes = [...new Set(plan.tasks.map(t => t.name.split(' ')[0]))]
      const summary = `This project plan outlines the development of ${plan.project_name} over a ${plan.total_duration}-day timeline. The project encompasses ${plan.tasks.length} key tasks including ${taskTypes.slice(0, 3).join(', ')}, and more. The plan includes task dependencies, resource allocation, and milestone tracking to ensure successful project delivery.`
      
      pdf.setFontSize(10)
      pdf.setFont('helvetica', 'normal')
      const summaryLines = pdf.splitTextToSize(summary, contentWidth)
      pdf.text(summaryLines, margin, yPos)
      yPos += summaryLines.length * 5 + 10

      // ========================================
      // 3. TASK BREAKDOWN TABLE
      // ========================================
      
      checkNewPage(40)
      pdf.setFontSize(16)
      pdf.setFont('helvetica', 'bold')
      pdf.text('TASK BREAKDOWN TABLE', margin, yPos)
      yPos += 10

      // Table header
      pdf.setFillColor(0, 0, 0)
      pdf.rect(margin, yPos, contentWidth, 10, 'F')
      
      pdf.setTextColor(255, 255, 255)
      pdf.setFontSize(9)
      pdf.setFont('helvetica', 'bold')
      pdf.text('#', margin + 2, yPos + 7)
      pdf.text('Task Name', margin + 10, yPos + 7)
      pdf.text('Duration', margin + 90, yPos + 7)
      pdf.text('Dependencies', margin + 115, yPos + 7)
      pdf.text('Owner', margin + 155, yPos + 7)
      yPos += 10

      // Table rows
      pdf.setTextColor(0, 0, 0)
      pdf.setFont('helvetica', 'normal')
      
      plan.tasks.forEach((task, index) => {
        checkNewPage(12)
        
        // Alternating row colors
        if (index % 2 === 0) {
          pdf.setFillColor(250, 250, 250)
          pdf.rect(margin, yPos, contentWidth, 10, 'F')
        }
        
        pdf.setFontSize(9)
        pdf.text(task.id.toString(), margin + 2, yPos + 7)
        
        const taskName = task.name.length > 35 ? task.name.substring(0, 35) + '...' : task.name
        pdf.text(taskName, margin + 10, yPos + 7)
        
        pdf.text(`${task.duration}d`, margin + 90, yPos + 7)
        
        const deps = task.dependencies && task.dependencies.length > 0 
          ? `Task ${task.dependencies.join(', ')}` 
          : 'None'
        pdf.text(deps, margin + 115, yPos + 7)
        
        pdf.text(task.owner, margin + 155, yPos + 7)
        
        yPos += 10
      })
      
      yPos += 10

      // ========================================
      // 4. GANTT CHART / TIMELINE VISUALIZATION
      // ========================================
      
      checkNewPage(60)
      pdf.setFontSize(16)
      pdf.setFont('helvetica', 'bold')
      pdf.text('GANTT CHART / TIMELINE VISUALIZATION', margin, yPos)
      yPos += 10

      // Draw timeline bars with proper spacing
      const barHeight = 10
      const maxDuration = plan.total_duration
      const barWidth = contentWidth - 70
      const taskNameWidth = 65
      
      // Add timeline scale
      pdf.setFontSize(8)
      pdf.setTextColor(100, 100, 100)
      pdf.text('0', margin + taskNameWidth, yPos)
      pdf.text(`${Math.floor(maxDuration/2)}`, margin + taskNameWidth + barWidth/2 - 5, yPos)
      pdf.text(`${maxDuration}`, margin + taskNameWidth + barWidth - 10, yPos)
      pdf.text('Days', margin + taskNameWidth + barWidth + 5, yPos)
      yPos += 5
      
      pdf.setTextColor(0, 0, 0)
      
      plan.tasks.forEach((task, index) => {
        checkNewPage(barHeight + 10)
        
        // Task name (left aligned, truncated if needed)
        pdf.setFontSize(9)
        pdf.setFont('helvetica', 'normal')
        const taskName = task.name.length > 28 ? task.name.substring(0, 28) + '...' : task.name
        pdf.text(taskName, margin, yPos + 7)
        
        // Timeline background bar
        pdf.setFillColor(245, 245, 245)
        pdf.setDrawColor(220, 220, 220)
        pdf.rect(margin + taskNameWidth, yPos, barWidth, barHeight, 'FD')
        
        // Calculate task bar position and width
        const startX = margin + taskNameWidth + (task.start_day / maxDuration) * barWidth
        const taskBarWidth = Math.max((task.duration / maxDuration) * barWidth, 3) // Minimum 3mm width
        
        // Task bar (black)
        pdf.setFillColor(0, 0, 0)
        pdf.rect(startX, yPos, taskBarWidth, barHeight, 'F')
        
        // Duration label (white text on black bar)
        pdf.setFontSize(7)
        pdf.setTextColor(255, 255, 255)
        if (taskBarWidth > 12) {
          const labelX = startX + taskBarWidth/2 - 4
          pdf.text(`${task.duration}d`, labelX, yPos + 6.5)
        }
        pdf.setTextColor(0, 0, 0)
        
        yPos += barHeight + 4
      })

      yPos += 15

      // ========================================
      // 5. MILESTONES / KEY DELIVERABLES
      // ========================================
      
      checkNewPage(40)
      pdf.setFontSize(16)
      pdf.setFont('helvetica', 'bold')
      pdf.text('MILESTONES / KEY DELIVERABLES', margin, yPos)
      yPos += 10

      // Identify milestones (tasks with no dependents or final tasks)
      const milestones = plan.tasks.filter(task => {
        const isDependent = plan.tasks.some(t => 
          t.dependencies && t.dependencies.includes(task.id)
        )
        return !isDependent || task.id === plan.tasks.length
      })

      milestones.forEach((milestone, index) => {
        checkNewPage(15)
        
        pdf.setFillColor(240, 240, 240)
        pdf.roundedRect(margin, yPos, contentWidth, 12, 2, 2, 'F')
        
        pdf.setFontSize(10)
        pdf.setFont('helvetica', 'bold')
        pdf.text(`Milestone ${index + 1}:`, margin + 3, yPos + 5)
        pdf.setFont('helvetica', 'normal')
        pdf.text(milestone.name, margin + 3, yPos + 9)
        
        pdf.setFontSize(8)
        pdf.setTextColor(100, 100, 100)
        pdf.text(`Day ${milestone.start_day + milestone.duration}`, margin + contentWidth - 25, yPos + 7)
        pdf.setTextColor(0, 0, 0)
        
        yPos += 15
      })

      yPos += 5

      // ========================================
      // 6. DETAILED TASK BREAKDOWN
      // ========================================
      
      checkNewPage(40)
      pdf.setFontSize(16)
      pdf.setFont('helvetica', 'bold')
      pdf.text('DETAILED TASK BREAKDOWN', margin, yPos)
      yPos += 10

      plan.tasks.forEach((task, index) => {
        checkNewPage(35)
        
        // Task box
        pdf.setDrawColor(200, 200, 200)
        pdf.setLineWidth(0.5)
        pdf.rect(margin, yPos, contentWidth, 30)
        
        // Task number circle
        pdf.setFillColor(0, 0, 0)
        pdf.circle(margin + 5, yPos + 8, 4, 'F')
        pdf.setTextColor(255, 255, 255)
        pdf.setFontSize(10)
        pdf.setFont('helvetica', 'bold')
        pdf.text(task.id.toString(), margin + 3.5, yPos + 9.5)
        
        // Task name
        pdf.setTextColor(0, 0, 0)
        pdf.setFontSize(11)
        pdf.setFont('helvetica', 'bold')
        pdf.text(task.name, margin + 12, yPos + 9)
        
        // Task details
        pdf.setFontSize(9)
        pdf.setFont('helvetica', 'normal')
        pdf.setTextColor(100, 100, 100)
        
        const detailsY = yPos + 18
        pdf.text(`Owner: ${task.owner}`, margin + 5, detailsY)
        pdf.text(`Start: Day ${task.start_day}`, margin + 60, detailsY)
        pdf.text(`Duration: ${task.duration} days`, margin + 100, detailsY)
        
        if (task.dependencies && task.dependencies.length > 0) {
          pdf.text(`Dependencies: Task ${task.dependencies.join(', ')}`, margin + 5, detailsY + 6)
        }
        
        yPos += 35
      })

      // ========================================
      // 7. SUMMARY METRICS
      // ========================================
      
      checkNewPage(50)
      pdf.setFontSize(16)
      pdf.setFont('helvetica', 'bold')
      pdf.setTextColor(0, 0, 0)
      pdf.text('SUMMARY METRICS', margin, yPos)
      yPos += 10

      // Metrics boxes
      const metrics = [
        { label: 'Total Tasks', value: plan.tasks.length.toString() },
        { label: 'Total Duration', value: `${plan.total_duration} days` },
        { label: 'Team Members', value: [...new Set(plan.tasks.map(t => t.owner))].length.toString() },
        { label: 'Dependencies', value: plan.tasks.filter(t => t.dependencies && t.dependencies.length > 0).length.toString() }
      ]

      const boxWidth = (contentWidth - 10) / 2
      const boxHeight = 25

      metrics.forEach((metric, index) => {
        const col = index % 2
        const row = Math.floor(index / 2)
        const x = margin + (col * (boxWidth + 5))
        const y = yPos + (row * (boxHeight + 5))

        // Box
        pdf.setFillColor(245, 245, 245)
        pdf.roundedRect(x, y, boxWidth, boxHeight, 2, 2, 'F')
        pdf.setDrawColor(220, 220, 220)
        pdf.roundedRect(x, y, boxWidth, boxHeight, 2, 2, 'S')

        // Label
        pdf.setFontSize(10)
        pdf.setFont('helvetica', 'bold')
        pdf.text(metric.label, x + 3, y + 10)

        // Value
        pdf.setFontSize(18)
        pdf.setFont('helvetica', 'bold')
        pdf.text(metric.value, x + 3, y + 20)
      })

      yPos += (Math.ceil(metrics.length / 2) * (boxHeight + 5)) + 10

      // Critical Dependencies
      const criticalTasks = plan.tasks.filter(t => 
        t.dependencies && t.dependencies.length > 1
      )

      if (criticalTasks.length > 0) {
        checkNewPage(30)
        pdf.setFontSize(12)
        pdf.setFont('helvetica', 'bold')
        pdf.text('Critical Dependencies:', margin, yPos)
        yPos += 7

        pdf.setFontSize(9)
        pdf.setFont('helvetica', 'normal')
        criticalTasks.forEach(task => {
          checkNewPage(8)
          pdf.text(`• ${task.name} depends on ${task.dependencies.length} tasks`, margin + 5, yPos)
          yPos += 5
        })
        yPos += 5
      }

      // ========================================
      // 8. TEAM ALLOCATION
      // ========================================
      
      checkNewPage(40)
      pdf.setFontSize(16)
      pdf.setFont('helvetica', 'bold')
      pdf.text('TEAM ALLOCATION', margin, yPos)
      yPos += 10

      const owners = [...new Set(plan.tasks.map(t => t.owner))]
      owners.forEach(owner => {
        checkNewPage(25)
        
        const ownerTasks = plan.tasks.filter(t => t.owner === owner)
        const totalDays = ownerTasks.reduce((sum, t) => sum + t.duration, 0)
        
        // Owner box
        pdf.setFillColor(250, 250, 250)
        pdf.rect(margin, yPos, contentWidth, 20, 'F')
        
        pdf.setFontSize(11)
        pdf.setFont('helvetica', 'bold')
        pdf.text(owner, margin + 5, yPos + 7)
        
        pdf.setFontSize(9)
        pdf.setFont('helvetica', 'normal')
        pdf.text(`${ownerTasks.length} tasks • ${totalDays} days total`, margin + 5, yPos + 13)
        
        yPos += 25
      })

      // ========================================
      // FOOTER ON ALL PAGES
      // ========================================
      
      const totalPages = pdf.internal.getNumberOfPages()
      const footerY = pageHeight - 12
      
      for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i)
        
        // Footer separator line
        pdf.setDrawColor(220, 220, 220)
        pdf.setLineWidth(0.5)
        pdf.line(margin, footerY - 3, pageWidth - margin, footerY - 3)
        
        // Footer text
        pdf.setFontSize(8)
        pdf.setFont('helvetica', 'normal')
        pdf.setTextColor(120, 120, 120)
        
        // Left: Generator
        pdf.text('Generated by Incept AI Project Planner', margin, footerY)
        
        // Center: Project name (truncated if too long)
        const centerText = plan.project_name.length > 40 
          ? plan.project_name.substring(0, 40) + '...' 
          : plan.project_name
        pdf.text(centerText, pageWidth / 2, footerY, { align: 'center' })
        
        // Right: Page number
        pdf.text(`Page ${i} of ${totalPages}`, pageWidth - margin, footerY, { align: 'right' })
      }

      // Save PDF
      const fileName = `${plan.project_name.replace(/\s+/g, '_')}_Project_Plan.pdf`
      pdf.save(fileName)
    } catch (error) {
      console.error('Error generating PDF:', error)
      alert('Failed to generate PDF. Please try again.')
    }
  }

  const handlePrint = () => {
    window.print()
  }

  return (
    <div 
      className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50"
      style={{ zIndex: 9999 }}
      onClick={onClose}
    >
      <div 
        className="bg-white rounded-lg shadow-xl max-w-6xl w-full max-h-[90vh] overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="bg-black text-white px-8 py-6 print:bg-white print:text-black print:border-b-2">
          <div className="flex justify-between items-start">
            <div className="flex-1">
              <h2 className="text-2xl font-bold mb-2">{plan.project_name}</h2>
              <div className="flex items-center gap-6 text-sm text-gray-300 print:text-gray-600">
                <span>Duration: {plan.total_duration} days</span>
                <span>•</span>
                <span>Tasks: {plan.tasks.length}</span>
                <span>•</span>
                <span>Generated: {new Date().toLocaleDateString()}</span>
              </div>
            </div>
            <div className="flex gap-2 print:hidden">
              <button 
                onClick={handleDownloadPDF}
                className="p-2 hover:bg-gray-800 rounded transition-colors"
                title="Download PDF"
              >
                <Download className="w-5 h-5" />
              </button>
              <button 
                onClick={handlePrint}
                className="p-2 hover:bg-gray-800 rounded transition-colors"
                title="Print Report"
              >
                <Printer className="w-5 h-5" />
              </button>
              <button
                onClick={onClose}
                className="p-2 hover:bg-gray-800 rounded transition-colors"
                title="Close"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
          </div>
        </div>

        {/* Content */}
        <div 
          ref={reportRef}
          className="p-8 overflow-y-auto max-h-[calc(90vh-140px)] bg-white"
        >
          {/* Executive Summary */}
          <div className="mb-8 pb-6 border-b-2 border-gray-200">
            <h3 className="text-xl font-bold text-gray-900 mb-4">Executive Summary</h3>
            <div className="grid grid-cols-3 gap-6">
              <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                <p className="text-sm text-gray-600 mb-1">Total Tasks</p>
                <p className="text-3xl font-bold text-gray-900">{plan.tasks.length}</p>
              </div>
              <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                <p className="text-sm text-gray-600 mb-1">Project Duration</p>
                <p className="text-3xl font-bold text-gray-900">{plan.total_duration}</p>
                <p className="text-xs text-gray-500">days</p>
              </div>
              <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
                <p className="text-sm text-gray-600 mb-1">Team Members</p>
                <p className="text-3xl font-bold text-gray-900">
                  {[...new Set(plan.tasks.map(t => t.owner))].length}
                </p>
              </div>
            </div>
          </div>

          {/* Project Timeline Section */}
          <div className="mb-10">
            <h3 className="text-xl font-bold text-gray-900 mb-4 pb-2 border-b-2 border-gray-200">
              Project Timeline
            </h3>
            <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
              <ResponsiveContainer width="100%" height={Math.max(400, plan.tasks.length * 60)}>
                <BarChart
                  data={chartData}
                  layout="vertical"
                  margin={{ top: 20, right: 40, left: 10, bottom: 20 }}
                  barCategoryGap="20%"
                >
                  <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" horizontal={false} />
                  <XAxis 
                    type="number" 
                    label={{ value: 'Days', position: 'insideBottom', offset: -10, style: { fontWeight: '600', fill: '#374151' } }}
                    stroke="#6b7280"
                    tick={{ fill: '#6b7280', fontSize: 12 }}
                  />
                  <YAxis 
                    dataKey="name" 
                    type="category" 
                    width={250}
                    stroke="#6b7280"
                    tick={{ fill: '#374151', fontSize: 12, fontWeight: '500' }}
                    interval={0}
                  />
                  <Tooltip 
                    content={({ active, payload }) => {
                      if (active && payload && payload.length) {
                        return (
                          <div className="bg-white p-4 rounded-lg shadow-xl border-2 border-gray-900">
                            <p className="font-bold text-gray-900 mb-2 text-sm">{payload[0].payload.fullName}</p>
                            <p className="text-xs text-gray-600 mb-1">
                              Days {payload[0].payload.start} - {payload[0].payload.end}
                            </p>
                            <p className="text-xs text-gray-900 font-semibold">
                              Duration: {payload[0].payload.duration} days
                            </p>
                          </div>
                        )
                      }
                      return null
                    }}
                    cursor={{ fill: 'rgba(0, 0, 0, 0.05)' }}
                  />
                  <Legend 
                    wrapperStyle={{ paddingTop: '20px' }}
                    iconType="rect"
                  />
                  <Bar 
                    dataKey="start" 
                    stackId="a" 
                    fill="#f3f4f6" 
                    name="Start Offset"
                  />
                  <Bar 
                    dataKey="duration" 
                    stackId="a" 
                    fill="#000000" 
                    name="Task Duration"
                    radius={[0, 4, 4, 0]}
                  />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Task Details Section */}
          <div className="mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4 pb-2 border-b-2 border-gray-200">
              Detailed Task Breakdown
            </h3>
            <div className="space-y-4">
              {plan.tasks.map((task) => (
                <div
                  key={task.id}
                  className="bg-white border-2 border-gray-200 rounded-lg p-5 break-inside-avoid"
                >
                  <div className="flex justify-between items-start mb-3">
                    <div className="flex items-start gap-3 flex-1">
                      <div className="w-10 h-10 bg-black text-white rounded flex items-center justify-center text-sm font-bold flex-shrink-0">
                        {task.id}
                      </div>
                      <div className="flex-1">
                        <h4 className="font-bold text-gray-900 text-lg mb-3">{task.name}</h4>
                        <div className="grid grid-cols-3 gap-4 text-sm">
                          <div className="flex items-center gap-2 text-gray-700">
                            <User className="w-4 h-4" />
                            <div>
                              <p className="text-xs text-gray-500">Owner</p>
                              <p className="font-semibold">{task.owner}</p>
                            </div>
                          </div>
                          <div className="flex items-center gap-2 text-gray-700">
                            <Calendar className="w-4 h-4" />
                            <div>
                              <p className="text-xs text-gray-500">Start Day</p>
                              <p className="font-semibold">Day {task.start_day}</p>
                            </div>
                          </div>
                          <div className="flex items-center gap-2 text-gray-700">
                            <Clock className="w-4 h-4" />
                            <div>
                              <p className="text-xs text-gray-500">Duration</p>
                              <p className="font-semibold">{task.duration} days</p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <span className="bg-gray-100 text-gray-700 px-3 py-1 rounded text-xs font-medium">
                      Task {task.id}
                    </span>
                  </div>

                  {task.dependencies && task.dependencies.length > 0 && (
                    <div className="mt-3 pt-3 border-t border-gray-200">
                      <p className="text-sm text-gray-600">
                        <span className="font-semibold">Dependencies:</span> Task {task.dependencies.join(', Task ')}
                      </p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Team Allocation */}
          <div className="mb-8">
            <h3 className="text-xl font-bold text-gray-900 mb-4 pb-2 border-b-2 border-gray-200">
              Team Allocation
            </h3>
            <div className="grid grid-cols-2 gap-4">
              {[...new Set(plan.tasks.map(t => t.owner))].map(owner => {
                const ownerTasks = plan.tasks.filter(t => t.owner === owner)
                const totalDays = ownerTasks.reduce((sum, t) => sum + t.duration, 0)
                return (
                  <div key={owner} className="bg-gray-50 border border-gray-200 rounded-lg p-4">
                    <h4 className="font-bold text-gray-900 mb-2">{owner}</h4>
                    <p className="text-sm text-gray-600 mb-2">
                      {ownerTasks.length} task{ownerTasks.length !== 1 ? 's' : ''} • {totalDays} days total
                    </p>
                    <ul className="text-sm text-gray-700 space-y-1">
                      {ownerTasks.map(t => (
                        <li key={t.id}>• {t.name}</li>
                      ))}
                    </ul>
                  </div>
                )
              })}
            </div>
          </div>

          {/* Footer */}
          <div className="mt-8 pt-6 border-t-2 border-gray-200 text-center text-sm text-gray-500">
            <p>Generated by Incept AI Project Planner</p>
            <p className="mt-1">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
          </div>
        </div>
      </div>

      <style jsx>{`
        @media print {
          .print\\:hidden {
            display: none !important;
          }
          .print\\:bg-white {
            background-color: white !important;
          }
          .print\\:text-black {
            color: black !important;
          }
          .print\\:border-b-2 {
            border-bottom: 2px solid #e5e7eb;
          }
        }
      `}</style>
    </div>
  )
}
